
pub const ERROR_400_HEADERS_READ_TIMEOUT: &str = "[400] HEADERS READ TIMEOUT";
pub const ERROR_400_HEADERS_READING_STREAM: &str = "[400] HEADERS READING STREAM";
pub const ERROR_400_HEADERS_FAILED_TO_PARSE: &str = "[400] HEADER FAILED TO PARSE";

pub const ERROR_400_BODY_SUM_CHUNK_SIZE_READ_TIMEOUT: &str =
"[400] BODY SUM CHUNK SIZE READ TIMEOUT";
pub const ERROR_400_BODY_SUM_CHUNK_SIZE_READING_STREAM: &str =
"[400] BODY SUM CHUNK SIZE READING STREAM";
pub const ERROR_400_BODY_SUM_CHUNK_SIZE_PARSE: &str =
"[400] BODY SUM CHUNK SIZE PARSE";
pub const ERROR_400_BODY_CHUNKED_BUT_ZERO_SUM_CHUNK_SIZE: &str =
"[400] BODY CHUNKED BUT ZERO SUM CHUNK SIZE";
pub const ERROR_400_BODY_CHUNK_SIZE_READ_TIMEOUT: &str =
"[400] BODY CHUNK SIZE READ TIMEOUT";
pub const ERROR_400_BODY_CHUNK_SIZE_READING_STREAM: &str =
"[400] BODY CHUNK SIZE READING STREAM";
pub const ERROR_400_BODY_CHUNK_SIZE_PARSE: &str =
"[400] BODY CHUNK SIZE PARSE";
pub const ERROR_400_BODY_CHUNK_READ_TIMEOUT: &str =
"[400] BODY CHUNK READ TIMEOUT";
pub const ERROR_400_BODY_CHUNK_READING_STREAM: &str =
"[400] BODY CHUNK READING STREAM";
pub const ERROR_400_BODY_CHUNK_IS_BIGGER_THAN_CHUNK_SIZE: &str =
"[400] BODY CHUNK IS BIGGER THAN CHUNK SIZE";
pub const ERROR_400_BODY_BUFFER_LENGHT_IS_BIGGER_THAN_CONTENT_LENGTH: &str =
"[400] BODY BUFFER LENGHT IS BIGGER THAN CONTENT LENGTH";
pub const ERROR_400_BODY_READ_TIMEOUT: &str =
"[400] BODY READ TIMEOUT";
pub const ERROR_400_DIRTY_BODY_READ_TIMEOUT: &str =
"[400] DIRTY BODY READ TIMEOUT";
pub const ERROR_400_BODY_READING_STREAM: &str =
"[400] BODY READING STREAM";


pub const ERROR_400_HEADER_BUFFER: &str = "[400] FAIL TO FILL HEADER BUFFER";
pub const ERROR_400_BODY_BUFFER: &str = "[400] FAIL TO FILL BODY BUFFER";